### ISSUE TITLE
I've finished writing that script! Needs improvements though . .. 

### ISSUE THREAD

**Issue by UsaidPro** [CodeBuds/Crevos#1]
So far, all it can do is access an _already compiled_ program called aa.out (when I'm tired, don't expect good file names). If aa.out allows arguments, it would run it without inputting any. Also, user cannot change the directory which it will look for to look for the file (and user cannot change the name it should look for!). Should I add these to my script?

~~1. Change directory to be 'checked' for file~~DONE
~~2. Change file name to be 'checked' for in directory~~DONE
3. Allow arguments to be passed to the need-to-run program (aa.out in this case)
4. Anything else?

~~Also, currently user has to go to '/usr/local/bin' in order to use the script (it is called a.out).~~(FIXED) Can either David or Eli make some sort of 'crevos command' (I'm not good at that sort of stuff yet!) which would run the script _regardless_ of which directory user is in? For example, if user is in $HOME/Downloads, the user can input 'crevos runcpp program' and it would still run the a.out script in /usr/local/bin
*_If this is too much info/complication (or you are just lazy) then just find me during lunch or project time . . . *_

**Comment by smerkousdavid** [comment]
This is done, as soon as I get the file

**Comment by UsaidPro** [comment]
I'll give you the file then . . . 
except that github doesn't support putting it inside a comment. Guess I'll try to share it with you another way . . ..

**Comment by smerkousdavid** [comment]
just create a new file in the depend folder located in the root folder of Crevos then I can take it from there

**Comment by UsaidPro** [comment]
I'm currently reinstalling Crevos so I can't upload the file from Chromebook. Wait for ~ten minutes  . . . .hopefully I'll have uploaded it by then.

**Comment by UsaidPro** [comment]
It is committed! Might not be usable for you though. . . . want me to give the .cpp version of it (not compiled to you) instead?

**Comment by smerkousdavid** [comment]
Sure, that would be better
