### ISSUE TITLE
Reinstall doesn't work

### ISSUE THREAD

**Issue by UsaidPro** [CodeBuds/Crevos#3]
After David's latest edit (on Sat. Oct 3rd) the 'crevos reinstall' command doesn't work. However, 'crevos updategrade' does. Error:

/usr/local/bin/crevos:384:in `<main>': undefined local variable or method`reinstall' for main:Object (NameError)

Looks like reinstall has been undefined. If this is true, then we should just remove it as a command/define it.

**Comment by smerkousdavid** [comment]
the command crevos reinstall doesn't work because the ruby file won't be able to update itself currently, so the work around I made is. Just run crevos-reinstall not crevos crevos-reinstall, just crevos-reinstall
