### ISSUE TITLE
For x11, why can't we do sudo apt-get?

### ISSUE THREAD

**Issue by UsaidPro** [CodeBuds/Crevos#4]
I think I'm making a dumb question here . . . but for x11, the way most do it is to do the phrase "sudo apt-get libx11-dev". Trying "crevos download libx11-dev" doesn't work, and when I check that is because we don't have sudo apt-get. Are we going to have a sudo apt-get? Considering installing most libraries depends on that, I don't see why we shouldn't have it.

**Comment by smerkousdavid** [comment]
Chromebooks are built off of gentoo which apt-get doesn't support... There's something called emerge which is similar to apt-get but for gentoo linux, but crashes on the chromebooks
