### ISSUE TITLE
Python 2.7?

### ISSUE THREAD

**Issue by UsaidPro** [CodeBuds/Crevos#5]
Crevos automatically install python version 3.3 when you run 'sudo crevos install python'. Option for version 2.7?

**Comment by smerkousdavid** [comment]
crevos remove python
crevos install python2.7

**Comment by UsaidPro** [comment]
The problem is that sudo crevos install python2.7 returns package not found. Chromebrew finds it though .. . . so what is missing? Since this is put on hold, I don't expect a quick response.

**Comment by eliliam** [comment]
We don't support python 2.7 in crevos I do you think
